stages:
  - deliver-image
  - deploy-production

variables:
  REPO_NAME: https://gitlab.rinznetwork.com/rinz-kingdom/core-api
  APP_NAME:  rzmusic_core_api

include:
  - project: 'devops/ci-pipeline'
    file: 'global.gitlab-ci.yml'
  - project: 'devops/ci-pipeline'
    file: 'deliver/.deliver.gitlab-ci.yml'
  - project: 'devops/ci-pipeline'
    file: 'util/.deploy_rzmusic.swarm.gitlab-ci.yml'
