version: "3"

services:
  api:
    container_name: rinz-music
    build: .
    restart: always
    volumes:
      - ./:/webapps
    ports:
      - 5000:5005
    environment:
      - PYTHONUNBUFFERED=true
    env_file:
      - .env
    # command: python manage.py run
    command: supervisord -n -c /etc/supervisor.d/supervisord.conf
    # command: tail -f /dev/null
