[unix_http_server]
file=/run/supervisord.sock   ; (the path to the socket file)

[supervisord]
logfile=/var/log/supervisord.log ; (main log file;default $CWD/supervisord.log)
loglevel=info                ; (log level;default info; others: debug,warn,trace)

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock ; use a unix:// URL  for a unix socket

[program:api-service]
command=uwsgi -psgi /etc/uwsgi/uwsgi.ini
directory=/webapps/api-service
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/apps/api.log

#[program:iapi_celery]
#command=celery --app code.tasks worker -Q card_issue_celery -l DEBUG -c 2
#directory=/webapps/thecuatui-service
#autostart=true
#autorestart=true
#redirect_stderr=true
#stdout_logfile=/var/log/apps/card_issue_celery.log
#logfile_maxbytes=10MB
#logfile_backups=1
