# -*- coding: utf-8 -*-

import os

# Response status
STATUS_OK = 1
STATUS_NOT_OK = 0

# Error code
NOT_E = ''
ERROR_MISSING_DATA = 'ERROR_MISSING_DATA'
ERROR_WRONG_DATA = 'ERROR_WRONG_DATA'

RZ_SHARE_WEBSITE = 'http://staging.rinzworld.com'

# FORMAT
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'

META_TYPE_TRACK_CATEGORY = 'track-category'
META_TYPE_AUTHOR_CATEGORY = 'rzm-author'

META_TYPES = [
    META_TYPE_TRACK_CATEGORY,
    META_TYPE_AUTHOR_CATEGORY,
]

USER_TYPE_NORMAL = ''
USER_TYPE_RAPPER = 'rapper'
USER_TYPE_CREATOR = 'creator'
USER_TYPES = [
    USER_TYPE_NORMAL,
    USER_TYPE_CREATOR,
    USER_TYPE_RAPPER,
]

USER_LEVEL_NORMAL = ''
USER_LEVEL_VIP = 'VIP'
USER_LEVEL_KOL = 'KOL'

USER_LEVELS = [
    USER_LEVEL_NORMAL,
    USER_LEVEL_KOL,
    USER_LEVEL_VIP,
]

RESOURCE_TYPE_EVENT = 'event'
RESOURCE_TYPE_TRACK = 'track'
RESOURCE_TYPE_MUSIC = 'music'
RESOURCE_TYPE_VIDEO = 'video'
RESOURCE_TYPE_IMAGE = 'image'
RESOURCE_TYPE_ALBUM = 'album'
RESOURCE_TYPE_TWEET = 'tweet'
RESOURCE_TYPE_IDOL = 'idol'
RESOURCE_TYPE_AUTHOR = 'author'
RESOURCE_TYPE_TWEET = 'tweet'

RESOURCE_TYPES = [
    RESOURCE_TYPE_EVENT,
    RESOURCE_TYPE_TRACK,
    RESOURCE_TYPE_MUSIC,
    RESOURCE_TYPE_VIDEO,
    RESOURCE_TYPE_IMAGE,
    RESOURCE_TYPE_TWEET,
]

RESOURCE_TYPE_ENCODEDS = [
    RESOURCE_TYPE_VIDEO,
    RESOURCE_TYPE_TRACK,
    RESOURCE_TYPE_MUSIC
]

REQUEST_ACTTIONS_METHODS = ['POST', 'PUT', 'DELETE']

STATUS_ACTIVE = 'active'
STATUS_INACTIVE = 'inactive'
STATUS_PROCESSING = 'processing'
STATUS_ENCODED = 'encoded'
STATUS_LIVE = 'live'
STATUS_LIVE_ENDED = 'live_ended'

MODE_PUBLIC = 'public'
MODE_PRIVATE = 'private'
MODE_FRIEND = 'friend'
TWEET_MODES = [
    MODE_PUBLIC,
    MODE_PRIVATE,
    MODE_FRIEND,
]

TRACKS_STATUS = [
    STATUS_ACTIVE,
    STATUS_INACTIVE,
    STATUS_PROCESSING,
    STATUS_ENCODED,
]

LIVE_STATUS = [
    STATUS_ACTIVE,
    STATUS_LIVE,
    STATUS_LIVE_ENDED
]

API_KEY_ENCODED = os.environ.get('API_KEY_ENCODED') or 'rzmusic@key'

VALIDATE_API_KEYS = [API_KEY_ENCODED]

# BLOCK DEFINE
BLOCK_SEARCH_BAR = "BLOCK_SEARCH_BAR"
BLOCK_IDOL_LIVE = "BLOCK_IDOL_LIVE"
BLOCK_WIDGET_ICONS = "BLOCK_WIDGET_ICONS"
BLOCK_SLIDER = "BLOCK_SLIDER"
BLOCK_TOP_IDOL = "BLOCK_TOP_IDOL"
BLOCK_NEW_FEED = "BLOCK_NEW_FEED"
BLOCK_TABS = "BLOCK_TABS"
BLOCK_NEW_TWEET = 'BLOCK_NEW_TWEET'

PAGE_SIZE_DEFAULT = 10

MUSIC_TYPE_ALL = 'all'
MUSIC_TYPE_HOT = 'hot'
MUSIC_TYPE_NEW = 'new'
MUSIC_TYPE_TRENDING = 'trending'

MUSIC_TYPES = [
    MUSIC_TYPE_ALL,
    MUSIC_TYPE_HOT,
    MUSIC_TYPE_NEW,
    MUSIC_TYPE_TRENDING,
]

COMMENT_TYPE_LIVE_CHAT = 'live_chat'
COMMENT_TYPE_NORMAL = 'normal'

SORT_TYPE_LASTEST = 'lastest'
SORT_TYPE_OLDEST = 'oldest'
SORT_TYPE_LIKE = 'like'

PAYMENT_STATUS_PAID = 'paid'
PAYMENT_STATUS_UNPAID = 'unpaid'
PAYMENT_RZ_MUSIC_GATEWAY = 'rinz-music'

RESP_MSG = {
    "payment_error": u"Tạm thời chưa thể thanh toán, vui lòng thử lại sau ít phút!",
    "payment_require": u"Vui lòng thanh toán để sử dụng Dịch Vụ, Xim cảm ơn!",
}
