# Response status
STATUS_OK = 1
STATUS_NOT_OK = 0

# Error code
NOT_E = ''
ERROR_MISSING_DATA = 'ERROR_MISSING_DATA'
ERROR_WRONG_DATA = 'ERROR_WRONG_DATA'

# FORMAT
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'

META_TYPE_TRACK_CATEGORY = 'track-category'

META_TYPES = [
    META_TYPE_TRACK_CATEGORY
]

USER_TYPE_NORMAL = ''
USER_TYPE_RAPPER = 'rapper'
USER_TYPE_CREATOR = 'creator'
USER_TYPES = [
    USER_TYPE_NORMAL,
    USER_TYPE_CREATOR,
    USER_TYPE_RAPPER,
]

USER_LEVEL_NORMAL = ''
USER_LEVEL_VIP = 'VIP'
USER_LEVEL_KOL = 'KOL'

USER_LEVELS = [
    USER_LEVEL_NORMAL,
    USER_LEVEL_KOL,
    USER_LEVEL_VIP,
]
